### PR TITLE
Add neomake

### LINKED ISSUE #42: Support for Neomake
It would be nice to have support for neomake. This is what I had to add to my `.vimrc` to get neomake colors working:

```
highlight NeomakeErrorMsg guifg=#DF8C8C
highlight NeomakeWarningMsg guifg=#F2C38F
let g:neomake_error_sign={'text': 'e', 'texthl': 'NeomakeErrorMsg'}
let g:neomake_warning_sign={'text': 'w', 'texthl': 'NeomakeWarningMsg'}
```

I'm not sure if this is the best way to make it work. If I leave off lines 3-4, then it doesn't show any characters next to the line numbers at all.

### PR DESCRIPTION
**Pull request by aharris88**
Fixes #42

### CODE REVIEW

**Comment by aharris88** [comment]
I couldn't run `npm start` because I'm on neovim. Also, I'm not sure if this is where you would want these lines of code or if you want them in a separate file. Also, not sure if I used the correct color groups, but I thought they should be red and orange (or maybe red and yellow).

**Comment by aharris88** [comment]
@trevordmiller That should fix all the changes requested.

**Comment by alexlafroscia** [comment]
@aharris88 can you add a screenshot of the change?

**Comment by aharris88** [comment]
screen shot 2016-10-13 at 4 26 53 pm

**Comment by aharris88** [comment]
I feel like maybe we shouldn't be putting the version numbers in the PR. I added `3.2.2` and another PR added `3.3.0`, so I'm not sure how that will work.

**Comment by alexlafroscia** [comment]
I agree, just commented the same thing on my PR. I wonder if a CI service could do that automatically after a successful merge into `master`...

**Comment by trevordmiller** [comment]
@aharris88 @alexlafroscia Yep, I agree. Left a comment on https://github.com/trevordmiller/nova-vim/issues/44. For this one, sorry Adam but Alex was first so I'm going to merge #41 then you'll need to pull and update your tag, then I'll merge this one.

**Comment by trevordmiller** [comment]
@aharris88 If you could update your version I'll merge this. Sorry for the hassle, we are discussing alternatives going forward on https://github.com/trevordmiller/nova-vim/issues/44

**Comment by aharris88** [comment]
I think I fixed the tag.

**Comment by trevordmiller** [comment]
@aharris88 Still shows you have a conflict 
image

**Comment by aharris88** [comment]
Ok, there we go.

**Comment by trevordmiller** [comment]
Thanks @aharris88. Merged.

**Comment by trevordmiller** [comment]
Try running your Vim plugin updates and make sure everything works as expected.

**Comment by alexlafroscia** [comment]
Pulled master and just tried it out, looks good to me.  I've been having issues with Neomake not showing the error symbol lately and never realized that it was a `colorscheme` issue.  Everything seems to be in order now.

**Comment by aharris88** [comment]
@trevordmiller Updated and it works!

**Pull request merged**
