### PR TITLE
Polish git diff styles

### PR DESCRIPTION
**Pull request by trevordmiller**
Closes https://github.com/trevordmiller/nova-vim/issues/83

### CODE REVIEW

**Comment by AodhanHayter** [comment]
Oh man, bummed on this change. Feel like it's harder to parse blocks of change with just text coloring instead of row highlighting. Just my personal preference though, will fork.

**Comment by trevordmiller** [comment]
@AodhanHayter Sorry about that. If you can find a good balance between what exists now and the issues mentioned in https://github.com/trevordmiller/nova-vim/issues/83 I'll happily accept a pull request so you don't need to fork.

**Comment by trevordmiller** [comment]
@AodhanHayter Woah, just realized you are the Aodhan I went to junior high and high school with - remember me? Small world :)

**Comment by AodhanHayter** [comment]
@trevordmiller Haha, yeah of course I remember you. Been a long time man. You probably don't run into many Aodhan's that spell their name like mine.

But yeah I looked at #83 and agree that it's not ideal that the diff styling doesn't override things such as the colorcolumn and cursor row. In my personal setup that doesn't really make a difference (no cursor row highlight, most code doesn't reach colorcolumn) and I prefer the background color change so it makes sense just to fork and merge releases periodically.

Really the only reason I commented is because this change threw me for a loop and I literally thought I had broken vimdiff somehow. Then I came to my senses and figured it must have been a change to the colorscheme, so I went hunting.

Because the default vimdiff styling is to color the background (correct me if I'm wrong) I think this kind of diverges from the typical vim experience which is good or bad based entirely on preference. I personally think it makes sense to stick with the default vimdiff styling sensibility, since that's what most people who use vimdiff are expecting, but really it just doesn't matter all that much when it's so simple for me to just fork and change it back.

But I would bet I'm not the only person that would be thrown off when viewing a diff and not seeing big blocks of highlighted changes.

Love the colorscheme, hope you're still shredding on the guitar. Don't waste a bunch of time fixing vimdiff styling for fools like me (I've already got my fork reverted).

**Comment by trevordmiller** [comment]
@AodhanHayter Good points 👍 I've reverted the vimdiff changes in a new release: https://github.com/trevordmiller/nova-vim/releases/tag/v3.14.0. So hopefully you won't need a fork anymore. I don't personally use vimdiff so let me know if you have any issues :)

**Comment by AodhanHayter** [comment]
@trevordmiller Awesome much easier to not maintain a fork. Thanks for all the work you've done with the nova-colors stuff, I really dig it. Hopefully we cross paths again sometime, it's been a long time since the good old FJH days.

**Pull request merged**
