### PR TITLE
Change vertical cursor color a bit

### PR DESCRIPTION
**Pull request by rizafahmi**
Make vertical cursor useful
screen shot 2017-06-23 at 3 53 35 pm

Compares to before
screen shot 2017-06-23 at 3 55 06 pm

### CODE REVIEW

**Comment by aharris88** [comment]
That looks nice.

**Comment by trevordmiller** [comment]
@rizafahmi, thank you for using Nova and for your contribution! I'll gladly merge and release it if you could please just update the source file instead of the built file (edits should be made in `src` and built automatically to the `colors/` directory); please see [CONTRIBUTING](the https://github.com/trevordmiller/nova-vim/blob/master/CONTRIBUTING.md) file for instructions. Here is an example of a pull request like this: https://github.com/trevordmiller/nova-vim/pull/59/files. Once you've updated the pull request, let me know and I'll merge and release it. Thank you :)

**Comment by trevordmiller** [comment]
Thanks @rizafahmi, this will go out in the next release

**Comment by rizafahmi** [comment]
@trevordmiller sorry, not reading contributing doc before. My bad :)

**Comment by trevordmiller** [comment]
@rizafahmi No worries :) Ok, this has been released in `3.10`. Please upgrade and let me know if you have any problems. Thanks again for using Nova!

**Comment by rizafahmi** [comment]
@trevordmiller all good. Thanks for Nova!

**Pull request merged**
