### PR TITLE
Add airline config

### LINKED ISSUE #21: Add colors for Airline
A lot of Vim users use [vim-airline](https://github.com/vim-airline/vim-airline), and having theme support there would be awesome!  For example, the Gruvbox theme does a nice job of providing an [Airline config file](https://github.com/morhetz/gruvbox/blob/master/autoload/airline/themes/gruvbox.vim).  Right now, it looks like this, which is not a great experience:

screen shot 2016-09-26 at 3 36 53 pm

### PR DESCRIPTION
**Pull request by alexlafroscia**
Add [`vim-airline`](https://github.com/vim-airline/vim-airline) theme.  I tried to leave as much documentation as I could to make it easy for people to update in the future without having to dig too far into the Airline documentation, which isn't super straight-forward when it comes to making custom themes.

Closes #21

### Normal
normal

### Insert Mode
insert

### Visual Mode
visual

### Replace Mode
replace

### "Inactive" Buffers
inactive

### Linting Errors/Warnings

If a plugin like Syntastic or Neomake provides errors or warnings, they'll appear in the bottom corner like so:

screen shot 2016-09-26 at 9 26 14 pm

Orange when it's reported as a warning, red for errors (although how well this works is dependent on the linter plugin; I've seen issues during testing where errors are reported as warnings and thus are displayed in orange.  Nothing we can do about that).

### Read-Only Buffers

By default, the little "lock" icon will be bright, bright red on read-only buffers, like a `:help` file.  I've colored it with the defined red color instead

screen shot 2016-09-26 at 9 53 53 pm

### Potential Holdups

For some reason, when you first open a buffer but haven't entered `insert` mode yet, the color of the bar is wrong (it should be `normal.black` but is instead `decoration.medium`).  I can't quite pin down what the issue is, but am working on it.  I'd say it's probably not a blocker, but hopefully I can just fix the issue and not worry about it.

screen shot 2016-09-26 at 10 03 17 pm

### CODE REVIEW

**Comment by trevordmiller** [comment]
Thank you for taking this on @alexlafroscia, I really appreciate the help. I'll review tomorrow and provide feedback. Once this is merged I'll be sure to share your work and we can add it to the Nova website.

**Comment by alexlafroscia** [comment]
Pushed some changes just now to manually set the Tabline colors (at the top of the window).  While Hyperterm had no issues without them being explicitly set, iTerm showed some of the colors wrong.  I also updated the background color behind the `tabtype` in the tabline to `nova.normal.green` to match the type color.

**Comment by trevordmiller** [comment]
@alexlafroscia This looks fantastic! Great work. Thank you for using my scripts and build process and for understanding the True Color support. I just have two questions and then I think we can merge this:
1) Do airline themes typically ship like this inside of the theme plugin with the `autoload` convention, or as a separate plugin?
2) Do you feel having different colors for each mode is helpful? To follow the Nova color meanings, I would probably prefer to have each of these be `normal.cyan`(to use the current user state meaning as I've done with other parts of editor UIs in the Vim and Atom plugins).

Sorry for my ignorance, I'm not a Vim airline user. @iammerrick will probably want to take a look at this too as he helped build the Vim theme and is an airline user.

**Comment by trevordmiller** [comment]
Nevermind, I did some research and it looks like what you did is the convention as is done in the [Oceanic Next theme]https://github.com/mhartington/oceanic-next) from @mhartington; nice work!
screen shot 2016-09-27 at 3 19 02 pm

**Comment by trevordmiller** [comment]
Once the updates have been made, here is what I plan to do:
- [ ] Add airline usage note to the documentation website (`let g:airline_theme='nova'`)
- [ ] Share on Twitter

**Comment by trevordmiller** [comment]
@alexlafroscia This looks fantastic! Great work. Thank you for using my scripts and build process and for understanding the True Color support. I really appreciate it. Do you mind if I request these tweaks?
- [ ] Do you feel having different colors for each mode is important? To follow the Nova color meanings, I would probably prefer to have each of these be `normal.cyan`(which represents current user state).
- [ ] Do you mind making warnings and errors both `normal.red` (represents user action required). `bright.red` (orange) represents "special" (like special symbols); I know that traditionally warnings are orange and errors are red, but in Nova color meanings red is anything that needs user action.
- [ ] Do you mind making the read-only lock icon `normal.cyan` since it is a part of user state (the file they have open), not something that requires action, right? Sorry for my ignorance, I'm not a Vim airline user.

Once the updates have been made, here is what I plan to do:
- [ ] Add airline usage note [to the Vim portion of the documentation website](https://github.com/trevordmiller/nova/blob/master/src/data/platforms.js#L18-L29) (`let g:airline_theme='nova'`)
- [ ] Tweet about it

@iammerrick will want to take a look at this too as he helped build the Vim theme and is an airline user.
@mhartington may be interested in reviewing as well since he is on the Airline team and helped review the Nova vim theme

**Comment by mhartington** [comment]
Nothing looks out of place

Might be nice to add a bit for Ctrlp Users

https://github.com/mhartington/oceanic-next/blob/master/autoload/airline/themes/oceanicnext.vim#L81

**Comment by iammerrick** [comment]
Wow @alexlafroscia this is some awesome work! Thank you! When I pull in your branch and install vim-airline I'm not quite getting the same results as your screenshots. Is there something I've missed perhaps? Is there something else I need to do? 

I am using Vim 8.0.7 and iTerm 2

- My tabs are not quite as nice as yours.
- My colors are different across the modes than yours. 

screen shot 2016-09-27 at 3 51 51 pm
screen shot 2016-09-27 at 3 51 32 pm
screen shot 2016-09-27 at 3 49 21 pm
screen shot 2016-09-27 at 3 49 18 pm

screen shot 2016-09-27 at 3 49 21 pm

**Comment by iammerrick** [comment]
I ran into similar issues with the syntastic and was also saddened when I couldn't change that bottom right error orange color.

**Comment by iammerrick** [comment]
# SHAME, OH THE SHAME

Literally all of those screenshots were from my earlier (clearly worse) attempt at support for Airline. :-D I reinstalled the plugin and installed your fork and didn't realize that my autoload had its own nova override. The shame is on me. 

This looks epic!

**Comment by iammerrick** [comment]
@alexlafroscia Thanks for teaching me I could enable tab line!

screen shot 2016-09-27 at 4 06 00 pm

**Comment by alexlafroscia** [comment]
@mhartington I can take a look at that, I don't use Ctrl-P myself, but I can install it to try to get the colors right.

@iammerrick Yup, Tabline is the solution there.  I also have been using [`vim-ctrlspace`](https://github.com/vim-ctrlspace/vim-ctrlspace) which might change it further.

@trevordmiller To address your bullet points:

1. I kind of do think that having a different color for each is important.  For my config, for example, that color is the only indication of what setting you're in, besides the text changing.  It's really up to you, using one for everything vs. different ones for each, but I personally like having a different color for each.
2. Sure, I can do that.
3. Sure, I can do that.

**Comment by aharris88** [comment]
> I kind of do think that having a different color for each is important.

I have to agree with this. I think most airline users would agree. But since Nova has a different definitions for the colors, I would be ok either way.

Also, I pulled the code from this PR and my colors don't look quite right:

screen shot 2016-09-27 at 6 42 38 pm

**Comment by alexlafroscia** [comment]
@aharris88 I'm having the same issue.  If you enter/exit insert mode, the background goes back to normal, right?  I can't figure out what exactly is wrong with it right now that's messing with that.

**Comment by alexlafroscia** [comment]
It just dawned on me -- that's the color of the default bottom line, without Airline, right?  Maybe the issue is on Airline's part, where the correct color is not applied right away?

**Comment by alexlafroscia** [comment]
I'm working on the linter output section and am not sure how I feel about changing warnings to red as well.

Airline just updated (I only got the changes today) to support Neomake properly.  It now shows the Error and Warning segments, even if they're empty.  For example, here is one Error and no Warnings with red/red and orange/red

screen shot 2016-09-27 at 11 21 43 pm
screen shot 2016-09-27 at 11 22 36 pm

I know that the colors have semantic means, but there's something to be said for the orange/red being separate instead. I personally feel like it's a better look but that's just me.

Airline also provides an option to hide empty sections which, apparently, doesn't play too nicely with these Neomake linter segments.  Again, red/red and then orange/red

screen shot 2016-09-27 at 11 28 07 pm
screen shot 2016-09-27 at 11 27 49 pm

(why the red/red shows no colors at all in that case, I have no idea).

**Comment by aharris88** [comment]
@alexlafroscia
 
>@aharris88 I'm having the same issue. If you enter/exit insert mode, the background goes back to normal, right?

This is when I first open up vim (neovim):

screen shot 2016-09-28 at 8 39 34 am

This is insert mode:

screen shot 2016-09-28 at 8 39 55 am

And this is after I go back to normal mode:

screen shot 2016-09-28 at 8 40 11 am

As you can see, the background does go back to normal, but the "arrow" color doesn't match the background of that section.

**Comment by trevordmiller** [comment]
@alexlafroscia @aharris88 @iammerrick Ok, let's keep the different colors per mode + warning/error differences that Alex originally built for the reasons mentioned above (I want the core of Nova to continue using the semantic color meanings only, but I'm ok with plugins using other colors in this way as has been suggested). @alexlafroscia thanks again for your great work on this; once you figure out the issues, let me know and I'll merge this in, add it to the website, and share it.

**Comment by alexlafroscia** [comment]
@trevordmiller sounds great! Just have to add the Ctrl-P colors; I'll get that in sometime today.

@aharris88 the wrong initial color has something to do with the default color of that bottom bar in the Vim theme, I suspect.  Might be an Airline bug, I'm not really sure.  The arrow color, I don't know about though.  Could be your font or something?  I use [Hasklig](https://github.com/i-tu/Hasklig) which comes pre-patched with the Powerline fonts.

**Comment by trevordmiller** [comment]
> "the wrong initial color has something to do with the default color of that bottom bar in the Vim theme, I suspect...I'd want to make sure that my suspicion of where that initial color is coming from is right." - @alexlafroscia 

This "bottom bar" is called the "Status Line" and which is defined in the `nova-vim` plugin source for both [inactive panes](https://github.com/trevordmiller/nova-vim/blob/master/src/index.js#L87) and [active panes](https://github.com/trevordmiller/nova-vim/blob/master/src/index.js#L118). I'd like to keep this as is as it matches all of the other Nova plugins for tabs (although we will be updating the inactive states of these "reverse" situations per https://github.com/trevordmiller/nova-colors/issues/21). I'm not sure how airline deals with the status line settings or the best way to use them together; might want to make sure that various status line settings work with this airline implementation (see `:help laststatus`).

**Comment by alexlafroscia** [comment]
Alright, I'll update the Airline status line config to match the default bg/fg colors

**Comment by trevordmiller** [comment]
@alexlafroscia sorry there has been so much back and forth on this. Let me know when you're ready and I'll merge and share it :)

**Comment by trevordmiller** [comment]
@alexlafroscia  I just released `nova-colors` `2.0.0` with a cleaner API for Nova color mappings to meanings; it's still the same color values, but the mappings should be easier to use for different contexts.

Here is what the full changes look like:
https://github.com/trevordmiller/nova-colors/pull/24/files

Here is an example of implementing the changes in an existing Nova plugin:
https://github.com/trevordmiller/nova-hyperterm/pull/12/files

Please update your plugin with this new API and we should be good to merge + add to the website and share :) Let me know when you are ready. Thank you again for your work!

**Comment by alexlafroscia** [comment]
@trevordmiller do you want me to update the `nova-colors` dependency to `2.0.0` then?

**Comment by alexlafroscia** [comment]
Nevermind: see #28

**Comment by trevordmiller** [comment]
@alexlafroscia How about we merge this pull request in (if you are ready?) and then I'll update everything (nova.vim and the airline file) together in https://github.com/trevordmiller/nova-vim/issues/25

**Comment by alexlafroscia** [comment]
Uh... Alright. I just did some updates to this PR to get the colors of the Airline status line to match better with the default colors, but it's all dependent on #28 landing first so...

**Comment by trevordmiller** [comment]
@alexlafroscia Sorry for the confusion. I'll merge in #28 and then this and I'll do #25 separately later.

**Comment by alexlafroscia** [comment]
Cool. I was able to fix the issue with the statusline having the wrong color initially, so I think all of the feedback was addressed (although I haven't added a Ctrl-P color scheme)

**Comment by trevordmiller** [comment]
> "Cool. I was able to fix the issue with the statusline having the wrong color initially, so I think all of the feedback was addressed (although I haven't added a Ctrl-P color scheme)" - @alexlafroscia 

Awesome. No worries.

**Comment by trevordmiller** [comment]
@alexlafroscia I'll merge this in once the conflict is resolved :) Thanks gain for all your work - you've been fantastic

**Comment by alexlafroscia** [comment]
@trevordmiller merge is fixed

**Comment by iammerrick** [comment]
Aww yeah can't wait to vim +PluginUpdate

**Comment by trevordmiller** [comment]
@alexlafroscia @iammerrick I am completing #25 and testing this out before adding it to the website and sharing it; I've never used airline before and it's not working for me:
Plugin 'vim-airline/vim-airline'
image
 
Relevant parts of my `.vimrc`:
```
...
Plugin 'vim-airline/vim-airline'
...
let g:airline_theme='nova'
```

This theme is a part of `nova-vim`, not `vim-airline-themes`, right? What other steps are needed other than installing the `vim-airline` plugin and declaring the `airline_theme` in the `.vimrc`?

**Comment by iammerrick** [comment]
It Just Works™ for me. after a +PluginUpdate

**Comment by trevordmiller** [comment]
Already ran a PluginUpdate; you don't have any other related rules or plugins in your `.vimrc`?

**Comment by iammerrick** [comment]
You don’t need to specify theme like that. Just using nova-vim is enough.

**Comment by trevordmiller** [comment]
Ok, I guess there is nothing to add to the website then if it just works for those that have airline installed

**Comment by iammerrick** [comment]
I think we should add airline support as a feature. Most themes don’t have that.

**Comment by trevordmiller** [comment]
@iammerrick Just a note right, no config required?

**Comment by iammerrick** [comment]
Yeah! Just something like. Airline Theme or something

**Comment by trevordmiller** [comment]
@iammerrick Will do

**Comment by trevordmiller** [comment]
Note added in https://github.com/trevordmiller/nova/pull/48

**Pull request merged**
