### PR TITLE
Update colors for tabs

### PR DESCRIPTION
**Pull request by maximmcnair**
Updated colors following conversation in https://github.com/trevordmiller/nova-vim/issues/81#issuecomment-329203835. Let me know if anything doesn't look right to you.

screen shot 2017-09-13 at 17 01 47

### CODE REVIEW

**Comment by agarrharr** [comment]
Looks much better! 👍

**Comment by trevordmiller** [comment]
Wonderful, thank you @maximmcnair for your contribution! I'll get this released tonight.

**Comment by trevordmiller** [comment]
This was released in https://github.com/trevordmiller/nova-vim/releases/tag/v3.11.0. Please upgrade and let me know if you have any problems. Thanks again @maximmcnair for your contribution!

**Comment by trevordmiller** [comment]
Closes https://github.com/trevordmiller/nova-vim/issues/81

**Pull request merged**
